version: '3.5'

services:
  postgres:
    container_name: gatewayql_postgres
    env_file: .env
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gatewayql
      - PGDATA=/data/postgres
    image: postgres
    ports:
      - "5432:5432"

