version: '3.5'

services:
  postgres:
    container_name: gatewayql_postgres
    env_file: .env
    environment: 
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-gatewayql}
      - PGDATA=/data/postgres
    image: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    restart: unless-stopped

