http:
  port: 3000

https:
  port: 3443
  tls: {}

admin:
  port: 9080  

apiEndpoints:
  api:
    host: '*'
    paths: /

serviceEndpoints:
  - name: 'demo'
    url: 'http://localhost:8044'
  - name: 'test'
    url: 'http://localhost:8045'

policies:
  - proxy
  - key-auth

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - key-auth:
          action:
            apiEndpoints: api
      - proxy:
          action:
            serviceEndpoint: demo