db:
  types: 
    type: 'postgres'
    retryAttempts: 3
    autoLoadEntities: true,
    synchronize: true
    host: 'postgres'
    port: 5432
    username: 'postgres'
    password: 'postgres'
    database: 'gatewayql'
    ssl: false
jwt_secret: 'secret'