db:
  types: 
    type: 'postgres'
    retryAttempts: 3
    autoLoadEntities: true,
    synchronize: true
    host: 'localhost'
    port: 5432
    username: 'postgres'
    password: 'postgres'
    database: 'gatewayql'
    ssl: false
crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10
jwt_secret: 'secret'